### ISSUE TITLE
old azure portal image

### ISSUE THREAD

**Issue by hongju** [MicrosoftDocs/powerbi-docs.ko-kr#414]
This article has very old feature image and description, so need update.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8b88d198-6022-4b58-7dca-abd17fbd8b5a
* Version Independent ID: da72fb29-713d-e133-0f45-2ecab458ead0
* Content: [Azure SQL Database에 대해 예약된 새로 고침의 문제 해결 - Power BI](https://docs.microsoft.com/ko-kr/power-bi/service-admin-troubleshooting-scheduled-refresh-azure-sql-databases)
* Content Source: [powerbi-docs/service-admin-troubleshooting-scheduled-refresh-azure-sql-databases.md](https://github.com/MicrosoftDocs/powerbi-docs.ko-kr/blob/live/powerbi-docs/service-admin-troubleshooting-scheduled-refresh-azure-sql-databases.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by srvbpigh** [comment]
Hello, @hongju
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1388](https://github.com/MicrosoftDocs/powerbi-docs/issues/1388) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @hongju

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/1388

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
